const CATEGORIES_ACTION_TYPES = {
  SET_CATEGORIES_MAP: "categories/SET_CATEGORIES_MAP",
  SET_CATEGORIES: "categories/SET_CATEGORIES",
  GET_ITEMS_STARTED: "categories/GET_ITEMS_STARTED",
  GET_ITEMS_SUCCESSFUL: "categories/GET_ITEMS_SUCCESSFUL",
  GET_ITEMS_FAILED: "categories/GET_ITEMS_FAILED",
};

export default CATEGORIES_ACTION_TYPES;
